name: ScamGuard
options:
  bundleIdPrefix: jp.police
  developmentLanguage: ja
  deploymentTarget:
    iOS: 17.0
targets:
  ScamGuard:
    type: application
    platform: iOS
    sources:
      - path: App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.police.ScamGuard
        INFOPLIST_FILE: App/Info.plist
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: ""
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: App/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication: []
        NSCalendarsUsageDescription: "警察庁推奨リストや防犯情報更新のために日付情報を利用します。"
    postCompileScripts: []
